### ISSUE TITLE
macos requirement for the virtiofs directory sharing becomes 12.0

### ISSUE THREAD

**Issue by ghost** [lab47/isle#1]
Regarding this: https://github.com/lab47/yalr4m/blob/c0870a44b422f220fab990780ad40882394fed6a/pkg/vz/README.md?plain=1#L16

Pretty much everything related to [shared directories](https://developer.apple.com/documentation/virtualization/shared_directories?changes=_3_3&language=objc) with the Virtualization Framework requires macOS 12.0.0+.

**Comment by evanphx** [comment]
Yeah, that's a vendored and modified dependency, I need do update that README.

**Comment by evanphx** [comment]
@protosam I see you're over in code-hex/vz as well! Once the shared directory stuff is merged in, I'll remove this vendor and go back to the main vz repo.

**Comment by ghost** [comment]
Didn't realize you were going to use `code-hex/vz`. Makes sense, I actually just found this repo because I was looking for examples of the hypervisor framework. Right now sockets elude me. lol

Going to go ahead and close this out then.
